//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BudgetManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int AccountID { get; set; }
        public int Category { get; set; }
        public string Memo { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
